name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Verificar versão do Python
      run: python --version
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes unitários
      run: pytest
    

    - name: Construir imagem Docker
      run: docker build -t my-flask-app .
