name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Verificar versão do Python
      run: python --version
    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Executar testes unitários
      run: pytest
    
    # Criar a imagem Docker
    - name: Construir imagem Docker
      run: docker build -t hello-world-app .

    # Executar o container na porta aleatória
    - name: Run Docker container on random port
      run: |
        docker run -d -p 0:5000 --name hello-world-container hello-world-app

